name = "netdisk-manager"
compatibility_date = "206-10-07"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "netdisk-history"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[[kv_namespaces]]
binding = "KV"
id = "REPLACE_WITH_YOUR_KV_ID"
